# Generated by Django 5.1.3 on 2024-11-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='stellar_secret_key',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stellar_secret_key',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
